### ISSUE TITLE
why is the component restriction from 1-9?

### ISSUE THREAD

**Issue by tamoyal** [bbrks/go-blurhash#5]
I get this error when trying to compute a 16x9 blurhash:

"blurhash: must have between 1 and 9 components"

But I can enter 16x9 here - https://blurha.sh/

So I'm curious why that limitation exists

**Comment by bbrks** [comment]
The website seems to limit the input of those fields to 9 behind the scenes. If you try using 10 the hash comes out the same as if you'd used 9.

I don't think there's a fundamental limitation in the algorithm for it being 9, but it reduces the efficiency of the hash for diminishing (or arguably worse) results on rendered hash.
