### ISSUE TITLE
Insanely slow

### ISSUE THREAD

**Issue by ivanjaros** [bbrks/go-blurhash#6]
PNG image 1000x1000 pixels and 366 kB in size takes 2.7 seconds to generate 5,5 quality hash. That is insanely slow. How come?

**Comment by ivanjaros** [comment]
When I resize a 111 kB image from 1000x1000 to 100x100, which takes 0 microseconds, computing 5,5 hash takes 25k microseconds(the 366 kB image took 28k microseconds). So the problem is the dimension of the image, clearly. Still, 2.7 seconds is too high. Maybe the resizing should be done internally by this library to avoid this unexpected performance penalty?

I used github.com/disintegration/imaging with NearestNeighbor resample filter for the resizing.

**Comment by bbrks** [comment]
It looks like it's a slow `math.Pow` via `sRGBToLinear` which has to run for each RGB value of each pixel in the input. Might be able to get away without doing the sRGB->linear conversion in the first place but I don't have time to spend looking further into this right now.

![Screenshot_20221109_103235](https://user-images.githubusercontent.com/1525809/200807359-cea2369b-7503-4441-8269-73aba50ffbfa.png)

So for now, I guess your approaches are:
- Resampling to a lower res prior to hashing
- Find a more optimised alternative to the stdlib `math.Pow`
- Find a more optimised alternative of the sRGB<->linear functions

**Comment by ivanjaros** [comment]
i think that adding the resizing is the way to go(even though it adds dependency on external library). as i said, the performance penalty seems to be non-factor.
```
func GetKnownBlurHash(mime string, src io.Reader) (string, error) {
	var img image.Image
	var err error

	switch mime {
	case "image/jpeg":
		img, err = jpeg.Decode(src)
	case "image/gif":
		img, err = gif.Decode(src)
	case "image/png":
		img, err = png.Decode(src)
	case "image/webp":
		img, err = webp.Decode(src)
	default:
		err = errors.New("unsupported image mime " + mime)
	}

	if err != nil {
		return "", err
	}

	img = imaging.Resize(img, 96, 0, imaging.NearestNeighbor)

	return blurhash.Encode(5, 5, img)
}

```
